### PR TITLE
Finalsplit

### PR DESCRIPTION
**Pull request by meggart**
These are the latest changes to split out the whole machinery to YAXArrays and leave the Geo-specific parts inside ESDL.jl

### CODE REVIEW

**Comment by meggart** [comment]
@felixcremer

**Comment by felixcremer** [comment]
I tested it, and the computations are working, but it feels slower as before, but I am not sure, whether this is also because I am currently not using the distributed computations.  And I have to set up proper tests to compare the timings of the different versions. 

I still can't open NetCDF files while the julia process is running but I can copy them and then they can be opened. 
But I now can't open my RQA results, but I am not sure, whether this is due to ESDL changes or my QGIS version, because the netcdf file looks ok, in ncdump. 
Could you test, whether you can open the file at
https://upload.uni-jena.de/data/5f3400804a46b4.93034284/lakecuberqa2.nc

I would also suggest, to not set the version number of YAXArrays directly to 1.0 because we still have some deprecations in there and I would also like to talk again about reducing the number of submodules. We could also think about renaming functions with cube in the name, because at the moment, this is a mix of Cube naming and YAXArray naming. 

I would suggest to first make the split and then we can tidy up YAXArrays further.

**Comment by meggart** [comment]
I just tested your file and could read it using NetCDF.jl without problems. I could not try ArchGDAL though, because I don't have the NetCDF driver installed. Otherwise I agree with your comments about version 1.0 and the removing of the remaining "cube" functions.

**Comment by felixcremer** [comment]
The type inference fails also for categorical axes.

**Comment by felixcremer** [comment]
What is the state of this? 
Is there anything I could help with to push this forward?

**Comment by meggart** [comment]
I think we can merge now. I have registered YAXArrays, so that the unit tests pass again now, so I think I will just do it....

**Pull request merged**
