### PR TITLE
Experimental function to construct an ESDLArray from envistacks

### PR DESCRIPTION
**Pull request by felixcremer**
This is only as a first start of the discussion, it is not at all 
polished and simply, so that we would construct the needed axes of the 
data to check whether it is working at all.
I can construct an ESDLArray with this, but the computation fails:
```julia
ERROR: MethodError: no method matching read!(::ArchGDAL.IDataset, ::PermutedDimsArray{Float32,3,(2, 3, 1),(3, 1, 2),Array{Float32,3}}, ::Array{Int32,1}, ::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  read!(::ArchGDAL.AbstractDataset, ::Array{#s58,3} where #s58<:Real, ::Array{Int32,1}, ::Integer, ::Integer, ::Integer, ::Integer) at /home/crem_fe/.julia/dev/ArchGDAL/src/raster/rasterio.jl:244
  read!(::ArchGDAL.AbstractDataset, ::Array{#s58,2} where #s58<:Real, ::Integer, ::Integer, ::Integer, ::Integer, ::Integer) at /home/crem_fe/.julia/dev/ArchGDAL/src/raster/rasterio.jl:231
  read!(::ArchGDAL.AbstractRasterBand, ::Array{#s58,2} where #s58<:Real, ::Integer, ::Integer, ::Integer, ::Integer) at /home/crem_fe/.julia/dev/ArchGDAL/src/raster/rasterio.jl:135
  ...
Stacktrace:
 [1] readblock!(::ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset}, ::PermutedDimsArray{Float32,3,(2, 3, 1),(3, 1, 2),Array{Float32,3}}, ::UnitRange{Int64}, ::UnitRange{Int64}, ::UnitRange{Int64}) at /home/crem_fe/.julia/dev/ArchGDAL/src/raster/array.jl:84
 [2] readblock!(::DiskArrays.PermutedDiskArray{Float32,3,PermutedDimsArray{Float32,3,(3, 1, 2),(2, 3, 1),ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset}}}, ::Array{Float32,3}, ::UnitRange{Int64}, ::UnitRange{Int64}, ::UnitRange{Int64}) at /home/crem_fe/.julia/dev/DiskArrays/src/permute_reshape.jl:80
 [3] getindex_disk(::DiskArrays.PermutedDiskArray{Float32,3,PermutedDimsArray{Float32,3,(3, 1, 2),(2, 3, 1),ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset}}}, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at /home/crem_fe/.julia/dev/DiskArrays/src/DiskArrays.jl:36
 [4] getindex(::DiskArrays.PermutedDiskArray{Float32,3,PermutedDimsArray{Float32,3,(3, 1, 2),(2, 3, 1),ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset}}}, ::UnitRange{Int64}, ::UnitRange{Int64}, ::UnitRange{Int64}) at /home/crem_fe/.julia/dev/DiskArrays/src/DiskArrays.jl:158
 [5] updatear(::Symbol, ::Tuple{UnitRange{Int64},UnitRange{Int64}}, ::ESDL.Cubes.ESDLArray{Float32,3,DiskArrays.PermutedDiskArray{Float32,3,PermutedDimsArray{Float32,3,(3, 1, 2),(2, 3, 1),ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset}}},Array{CubeAxis,1}}, ::Int64, ::Array{Int64,1}, ::Array{Float32,3}) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:334
 [6] (::ESDL.DAT.var"#54#55"{Tuple{UnitRange{Int64},UnitRange{Int64}},Symbol})(::ESDL.DAT.InputCube{3}) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:319
 [7] foreach at ./abstractarray.jl:1920 [inlined]
 [8] updatears(::Tuple{ESDL.DAT.InputCube{3}}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}, ::Symbol) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:318
 [9] updateinars(::ESDL.DAT.DATConfig{1,1}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:340
 [10] runLoopArgs(::ESDL.DAT.DATConfig{1,1}, ::Tuple{ESDL.DAT.var"#50#52"{ESDL.DAT.var"#50#51#53"{typeof(mean)}},Tuple{Array{Float32,3}},Tuple{Array{Union{Missing, Float32},2}},Tuple{ESDL.ESDLTools.PickAxisArray{Float32,2,Array{Float32,3},(1, 2),1}},Tuple{ESDL.ESDLTools.PickAxisArray{Union{Missing, Float32},2,Array{Union{Missing, Float32},2},(1, 2),0}},Tuple{Tuple{ESDL.DAT.AllMissing}},Tuple{Array{Array{Float32,1},1}},Tuple{Array{Array{Union{Missing, Float32},0},1}},ESDL.DAT.NoLoopAxes,Tuple{},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}}, ::Base.Iterators.ProductIterator{Tuple{Array{UnitRange{Int64},1},Array{UnitRange{Int64},1}}}, ::Bool) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:412
 [11] runLoop(::ESDL.DAT.DATConfig{1,1}, ::Base.Iterators.ProductIterator{Tuple{Array{UnitRange{Int64},1},Array{UnitRange{Int64},1}}}, ::Bool) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:406
 [12] runLoop(::ESDL.DAT.DATConfig{1,1}, ::Bool) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:350
 [13] #mapCube#43(::Float64, ::InDims, ::OutDims, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Array{Int64,1}, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(mapCube), ::typeof(mean), ::Tuple{ESDL.Cubes.ESDLArray{Float32,3,ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset},Array{CubeAxis,1}}}) at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:272
 [14] (::ESDL.DAT.var"#kw##mapCube")(::NamedTuple{(:indims, :outdims, :inplace),Tuple{InDims,OutDims,Bool}}, ::typeof(mapCube), ::Function, ::Tuple{ESDL.Cubes.ESDLArray{Float32,3,ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset},Array{CubeAxis,1}}}) at ./none:0
 [15] #mapslices#42 at /home/crem_fe/.julia/dev/ESDL/src/DAT/DAT.jl:178 [inlined]
 [16] (::Base.var"#kw##mapslices")(::NamedTuple{(:dims,),Tuple{String}}, ::typeof(mapslices), ::Function, ::ESDL.Cubes.ESDLArray{Float32,3,ArchGDAL.RasterDataset{Float32,ArchGDAL.IDataset},Array{CubeAxis,1}}) at ./none:0
 [17] top-level scope at REPL[16]:1
```

### CODE REVIEW

**Comment by meggart** [comment]
Do you have a small ENVI stack for testing? I want to work on a GDAL backend, but currently lack nice testing data.

**Comment by felixcremer** [comment]
Yes, 
https://upload.uni-jena.de/data/5e985b72ce5d57.03129306/small_envistack.zip
this is a very small envistack, but it should work as a test case. 
Feel free to contact me, if I could be of any help.

**Comment by meggart** [comment]
On the SplitPackages branch the following works now:

````julia
using ArchGDAL
const AG = ArchGDAL
f = AG.readraster("./small_envistack")

using ESDL
#We can not avoid converting to an ESDLArray, however this works generically
c = ESDLArray(f)

# And do some analysis
using Statistics
indims = InDims("Band")
outdims = OutDims()
func(xout,xin) = xout[] = mean(skipmissing(xin))
cm = mapCube(func, c, indims = indims, outdims=outdims)

# Or use it as a cubing tool
savecube(c,"./mynewcube.zarr",chunksize = (2,2,271))
c2 = Cube("./mynewcube.zarr")
````

This was done by implementing the yaxarray traits for RasterDatasets and for GDALBands. So the same conversions to ESDLArrays work for DimensionalArrays and for AxisArrays. It is not yet possible to call mapCube directly on the RasterDataset object, because mapCube currently does `permutedims` which returns a PermutedDiskArray and this one does not implement the YAXArray interface. This can be solved in the future if needed, but I think the current approach should work as well. 

````

**Comment by felixcremer** [comment]
This looks very promising. Is this also supposed to work for other data types which could be opened by GDAL? For example Tiff, or GDAL VRT?
If I would reuse this cube often, then it would be best to save it directly as a zarrcube in a proper chunksize right?
When I find problems with this, where should I report them?

**Comment by meggart** [comment]
> This looks very promising. Is this also supposed to work for other data types which could be opened by GDAL? For example Tiff, or GDAL VRT?

There is nothing specific to ENVI stacks in this code, so yes it should work for every GDAL-opened dataset. 

> If I would reuse this cube often, then it would be best to save it directly as a zarrcube in a proper chunksize right?

Yes, this is the way to go and ideally all you need to do is to call the savecube with the new chunk size, although there is probably a lot to be optimized there in terms of performance. If you run a test on this, let me know if this is much slower than what you did with esdl-core before. 

> When I find problems with this, where should I report them?

Maybe directly in the SplitPackages PR

**Comment by meggart** [comment]
I guess we can close this now that there is GDAL support through YAXArrayBase? Or do we need to define something along the lines of 

````julia
gdalcube(path) = YAXArray(AG.readraster(path))
````

**Comment by felixcremer** [comment]
I think we can close this now and rather add some documentation how to load gdal datasets with YAXArrays. 
The best would be when we could get it to make `Cube(path) = YAXArray(AG.readraster(path))` and we get this dispatch either from the file extension or we can have a backend keyword similar to the behaviour of savecube.

**Pull request closed without merging**
